zookeeper.connectString: localhost:42181
zookeeper.sessionTimeout: 1000
cluster.root: /waltz_cluster

DataSource:
  ConnectString: jdbc:mysql://localhost:43306/DEMO_BANK?useSSL=false
  Username: demo
  Password: demo

